### ISSUE TITLE
version issue?

### ISSUE THREAD

**Issue by LucaMoiana** [calvinmetcalf/leaflet.filegdb#4]
Hi, for a work task I have to create a leaflet frome esri GDB.
I found out about leaflet.fgdb.js, (https://github.com/calvinmetcalf/leaflet.filegdb), but I can't get it to work with my GDB (I tested the GDB uploading it on http://calvinmetcalf.github.io/fileGDB.js.

So, what is wrong with my code?

my folder structure:

index.html
    |-JS
      |-map.js
    |-DATA
     |-nidi.gdb
     |-nidi.gdb.zip

My file gdb is created using ArcGIS 10.1

Code can be found here: https://groups.google.com/d/msg/leaflet-js/EAELTM3TXwA/rjBoAMkIeHYJ

**Comment by calvinmetcalf** [comment]
If you are new to JavaScript you are probably better off just converting
your data to geojson, this plugin is pretty experimental.

**Comment by LucaMoiana** [comment]
I know, but I do need to use gdb :(
thanks anyway

**Comment by calvinmetcalf** [comment]
Then can you post your code on gist.github.com. Along with the stack traces
of your errors (you can get these by removing the script tag that loads
catiline so it runs in the main thread)

**Comment by LucaMoiana** [comment]
here is the repo witha sample dat https://github.com/LucaMoiana/filegdbtest

**Comment by calvinmetcalf** [comment]
leaflet and fgdb need to be loaded before leaflet.fgdb
